from typing import Dict, List, Optional, Any
from datetime import datetime, timedelta, timezone
from ..core.config import settings
from ..utils.logger import get_logger
from ..utils.db import (
    get_db_connection,
    normalize_placeholders,
    execute_insert_and_get_id,
)
from .openrouter_service import openrouter_service, RateLimitError
from .news_service import news_service
from .multi_exchange_price_service import multi_exchange_price_service

logger = get_logger("backend.app.services.ai_advisor_service")


class AIAdvisorService:
    """Main service for AI advisor predictions and analysis"""

    def __init__(self):
        self.model_name = settings.openrouter_model

    async def generate_predictions(
        self, user_id: Optional[int], symbol: str, force_regenerate: bool = False
    ) -> Dict[str, Any]:
        """
        Generate or retrieve AI predictions for a symbol (global for all users)
        
        Args:
            user_id: User ID (optional, None for global predictions stored with user_id = NULL)
            symbol: Cryptocurrency symbol
            force_regenerate: If True, regenerate even if recent predictions exist

        Returns:
            Dictionary with predictions for 24h, week, month, year
        """
        symbol_upper = symbol.upper()
        
        # Check if we have cached global predictions first (user_id IS NULL)
        existing = self._get_latest_predictions(symbol_upper)
        if existing:
            # Check if predictions are still fresh (within interval)
            # Handle both datetime objects and string timestamps from database
            created_at_value = existing[0]["created_at"]
            if isinstance(created_at_value, datetime):
                created_at = created_at_value
                # Ensure timezone-aware (replace naive datetime with UTC)
                if created_at.tzinfo is None:
                    created_at = created_at.replace(tzinfo=timezone.utc)
            elif isinstance(created_at_value, str):
                # Replace Z with +00:00 for ISO format compatibility
                created_at = datetime.fromisoformat(created_at_value.replace("Z", "+00:00"))
                # Ensure timezone-aware
                if created_at.tzinfo is None:
                    created_at = created_at.replace(tzinfo=timezone.utc)
            else:
                # Fallback: try to parse as string
                created_at = datetime.fromisoformat(str(created_at_value).replace("Z", "+00:00"))
                # Ensure timezone-aware
                if created_at.tzinfo is None:
                    created_at = created_at.replace(tzinfo=timezone.utc)
            age = datetime.now(timezone.utc) - created_at
            if age < timedelta(hours=settings.ai_prediction_interval_hours):
                logger.debug(
                    f"Using existing global predictions for {symbol_upper} (age: {age})"
                )
                return self._format_predictions_response(existing)
        
        # Check for any cached predictions as fallback (even if old)
        cached = self._get_cached_predictions_fallback(symbol_upper, max_age_days=None, include_verified=True)
        if cached and not force_regenerate:
            logger.info(f"Returning cached predictions for {symbol_upper} (force_regenerate=False)")
            return cached
        
        # If force_regenerate=False, only return existing predictions (never generate on-demand)
        # Predictions should only be generated by background task to avoid rate limits
        if not force_regenerate:
            if existing:
                logger.debug(f"Returning existing predictions for {symbol_upper} (even if old, force_regenerate=False)")
                return self._format_predictions_response(existing)
            else:
                # No predictions exist - return empty dict (will be handled gracefully by API)
                logger.debug(f"No predictions found for {symbol_upper}, returning empty (predictions will be generated by background task)")
                return {}

        # Only generate new predictions if force_regenerate=True (background task or manual trigger)
        try:
            # Get current price
            prices = await multi_exchange_price_service.get_current_prices([symbol_upper])
            if symbol_upper not in prices:
                logger.warning(f"Could not fetch current price for {symbol_upper}")
                return {}

            current_price = prices[symbol_upper]

            # Get price trend (need to calculate from history or use simple approximation)
            price_trend = await self._get_price_trend(symbol_upper)

            # Get news
            articles = await news_service.fetch_news(symbol_upper, days=7)
            news_summary = news_service.get_news_summary(articles)
            news_sentiment = news_service.get_average_sentiment(articles)

            # Generate predictions using OpenRouter (only for BTC)
            try:
                predictions_response = await openrouter_service.generate_prediction(
                    symbol=symbol_upper,
                    current_price=current_price,
                    price_trend=price_trend,
                    news_summary=news_summary,
                    news_sentiment=news_sentiment,
                    news_articles=articles[:5],  # Pass top 5 articles for source references
                )

                # Extract predictions
                predictions_dict = predictions_response.get("predictions", {})
                if not predictions_dict:
                    logger.warning(f"No predictions returned from OpenRouter for {symbol_upper}")
                    # Fallback to cached predictions
                    return self._get_cached_predictions_fallback(symbol_upper)

                # Store predictions in database
                # Use isoformat() which includes timezone offset (e.g., +00:00) - PostgreSQL compatible
                now = datetime.now(timezone.utc).isoformat()
                
                # Clean up old global predictions for this symbol to avoid duplicates
                self._cleanup_old_predictions(symbol_upper, user_id=user_id)
                
                stored_predictions = []

                # Store predictions globally (user_id = NULL for global predictions)
                # If user_id is None, store with NULL; otherwise use provided user_id
                for pred_type, pred_data in predictions_dict.items():
                    if pred_type in ["24h", "week", "month", "year"]:
                        # Validate predicted_price - must be provided and different from current_price
                        predicted_price = pred_data.get("predicted_price")
                        if predicted_price is None:
                            logger.warning(f"Missing predicted_price for {symbol_upper} {pred_type}, skipping")
                            continue
                        
                        # Ensure predicted_price is different from current_price (allow small tolerance for rounding)
                        if abs(predicted_price - current_price) < 0.0001:
                            logger.warning(f"Predicted price {predicted_price} equals current price {current_price} for {symbol_upper} {pred_type}, skipping")
                            continue
                        
                        # Enhance reasoning with news source links
                        reasoning = pred_data.get("reasoning", "")
                        reasoning_with_sources = self._add_news_source_links(
                            reasoning, articles[:5]
                        )
                        
                        prediction_id = self._store_prediction(
                            user_id=user_id,  # None for global predictions, or user_id if provided
                            symbol=symbol_upper,
                            prediction_type=pred_type,
                            predicted_price=predicted_price,
                            confidence_percent=pred_data.get("confidence_percent", 50),
                            reasoning=reasoning_with_sources,
                            model_name=self.model_name,
                            created_at=now,
                        )
                        stored_predictions.append(
                            {
                                "id": prediction_id,
                                "prediction_type": pred_type,
                                "predicted_price": predicted_price,
                                "confidence_percent": pred_data.get("confidence_percent", 50),
                                "reasoning": reasoning_with_sources,  # Use reasoning with source links
                                "model_name": self.model_name,
                                "created_at": now,
                                "is_verified": False,
                            }
                        )

                logger.info(
                    f"Generated and stored {len(stored_predictions)} predictions for {symbol_upper}"
                )

                return self._format_predictions_response(stored_predictions)
            
            except RateLimitError as e:
                # Rate limit hit - return cached predictions if available
                logger.warning(f"Rate limit hit for {symbol_upper}, falling back to cached predictions")
                cached = self._get_cached_predictions_fallback(symbol_upper, max_age_days=None, include_verified=True)
                if cached:
                    logger.info(f"Returning cached predictions for {symbol_upper}")
                    return cached
                # If no cache, return empty dict (background task will generate later)
                logger.warning(f"No cached predictions available for {symbol_upper} after rate limit")
                return {}

        except RateLimitError as e:
            # Rate limit error - try to return cached predictions, otherwise return empty
            logger.warning(f"Rate limit error for {symbol_upper}: {e}")
            cached = self._get_cached_predictions_fallback(symbol_upper, max_age_days=None, include_verified=True)
            if cached:
                logger.info(f"Returning cached predictions for {symbol_upper} after rate limit")
                return cached
            return {}
        except Exception as e:
            logger.error(
                f"Error generating predictions for {symbol_upper}: {e}", exc_info=True
            )
            # Try to return cached predictions as fallback (any age, including verified)
            # This handles connection errors, timeouts, etc.
            cached = self._get_cached_predictions_fallback(symbol_upper, max_age_days=None, include_verified=True)
            if cached:
                logger.info(f"Returning cached predictions for {symbol_upper} due to error: {e}")
                return cached
            # If no cache available, return empty dict
            logger.warning(f"No cached predictions available for {symbol_upper} after error: {e}")
            return {}

    def _add_news_source_links(
        self, reasoning: str, articles: List[Dict[str, Any]]
    ) -> str:
        """Add clickable news source links to the reasoning text"""
        if not articles:
            return reasoning if reasoning else ""
        
        import re
        
        # Build source links for all available articles
        source_links = []
        for idx, article in enumerate(articles[:5], 1):  # Top 5 sources
            url = article.get("url", "")
            if url:
                # Ensure URL is absolute (external)
                if not url.startswith(('http://', 'https://')):
                    url = f"https://{url}"
                source_links.append(f"[{idx}]({url})")
        
        if not source_links:
            return reasoning if reasoning else ""
        
        # Pattern to match [number] references that are NOT already markdown links
        # This matches [1], [2] but not [1](url) which is already a link
        pattern = r'\[(\d+)\](?!\()'
        
        # Replace standalone references [1], [2] with markdown links [1](url)
        def replace_ref(match):
            idx = int(match.group(1))
            if 1 <= idx <= len(articles):
                article = articles[idx - 1]
                url = article.get("url", "")
                if url:
                    # Ensure URL is absolute (external)
                    if not url.startswith(('http://', 'https://')):
                        url = f"https://{url}"
                    return f"[{idx}]({url})"
            return match.group(0)  # Return original if no valid article
        
        # Replace any standalone references with markdown links
        reasoning = re.sub(pattern, replace_ref, reasoning)
        
        # Always append source links section at the end for easy access
        # Check if sources section already exists
        if "Sources:" not in reasoning and "sources:" not in reasoning.lower():
            reasoning = (reasoning + "\n\nSources: " + ", ".join(source_links)).strip()
        elif source_links:
            # If sources section exists but links are missing, append them
            # Only append if not already present
            existing_links = re.findall(r'\[(\d+)\]\([^)]+\)', reasoning)
            missing_links = [link for link in source_links if link not in reasoning]
            if missing_links:
                reasoning += ", " + ", ".join(missing_links)
        
        return reasoning

    async def _get_price_trend(self, symbol: str) -> Dict[str, float]:
        """Get price trend data for a symbol"""
        # For now, return a simple structure
        # In production, this could fetch historical data and calculate trends
        return {
            "change_7d": 0.0,
            "change_30d": 0.0,
            "volatility": 0.0,
        }

    def _get_latest_predictions(
        self, symbol: str, include_verified: bool = False
    ) -> Optional[List[Dict[str, Any]]]:
        """Get the latest global predictions for a symbol (shared across all users)
        
        Args:
            symbol: Cryptocurrency symbol
            include_verified: If True, also include verified predictions (used as fallback)
        """
        try:
            conn = get_db_connection()
            cursor = conn.cursor()

            # Get global predictions (user_id IS NULL for centralized predictions)
            # Prioritize global predictions (user_id IS NULL) over user-specific ones
            if include_verified:
                sql = normalize_placeholders(
                    """
                    SELECT id, prediction_type, predicted_price, confidence_percent,
                           prediction_reasoning, model_name, created_at, is_verified,
                           actual_price_at_target, accuracy_percent
                    FROM ai_predictions
                    WHERE symbol = %s
                    ORDER BY (CASE WHEN user_id IS NULL THEN 0 ELSE 1 END), is_verified ASC, created_at DESC
                    LIMIT 4
                """
                )
            else:
                sql = normalize_placeholders(
                    """
                    SELECT id, prediction_type, predicted_price, confidence_percent,
                           prediction_reasoning, model_name, created_at, is_verified,
                           actual_price_at_target, accuracy_percent
                    FROM ai_predictions
                    WHERE symbol = %s AND is_verified = FALSE
                    ORDER BY (CASE WHEN user_id IS NULL THEN 0 ELSE 1 END), created_at DESC
                    LIMIT 4
                """
                )
            cursor.execute(sql, (symbol.upper(),))
            rows = cursor.fetchall()
            conn.close()

            if rows:
                predictions = []
                for row in rows:
                    predictions.append(
                        {
                            "id": row[0],
                            "prediction_type": row[1],
                            "predicted_price": row[2],
                            "confidence_percent": row[3],
                            "reasoning": row[4],
                            "model_name": row[5],
                            "created_at": row[6],
                            "is_verified": bool(row[7]) if len(row) > 7 else False,
                            "actual_price_at_target": row[8] if len(row) > 8 else None,
                            "accuracy_percent": row[9] if len(row) > 9 else None,
                        }
                    )
                return predictions

        except Exception as e:
            logger.error(
                f"Error fetching latest predictions for {symbol}: {e}", exc_info=True
            )

        return None

    def _get_cached_predictions_fallback(
        self, symbol: str, max_age_days: Optional[int] = 7, include_verified: bool = False
    ) -> Optional[Dict[str, Any]]:
        """Get cached predictions as fallback when API fails (less strict age check)
        
        Args:
            symbol: Cryptocurrency symbol
            max_age_days: Maximum age in days (None = no age limit, return any cached predictions)
            include_verified: If True, also check for verified predictions
        """
        try:
            existing = self._get_latest_predictions(symbol, include_verified=include_verified)
            if existing:
                # Handle both datetime objects and string timestamps from database
                created_at_value = existing[0]["created_at"]
                if isinstance(created_at_value, datetime):
                    created_at = created_at_value
                    # Ensure timezone-aware (replace naive datetime with UTC)
                    if created_at.tzinfo is None:
                        created_at = created_at.replace(tzinfo=timezone.utc)
                elif isinstance(created_at_value, str):
                    # Replace Z with +00:00 for ISO format compatibility
                    created_at = datetime.fromisoformat(created_at_value.replace("Z", "+00:00"))
                    # Ensure timezone-aware
                    if created_at.tzinfo is None:
                        created_at = created_at.replace(tzinfo=timezone.utc)
                else:
                    # Fallback: try to parse as string
                    created_at = datetime.fromisoformat(str(created_at_value).replace("Z", "+00:00"))
                    # Ensure timezone-aware
                    if created_at.tzinfo is None:
                        created_at = created_at.replace(tzinfo=timezone.utc)
                age = datetime.now(timezone.utc) - created_at
                
                # If max_age_days is None, return any cached predictions regardless of age
                if max_age_days is None or age < timedelta(days=max_age_days):
                    logger.debug(
                        f"Using cached predictions for {symbol} (age: {age}, max_age: {max_age_days} days)"
                    )
                    return self._format_predictions_response(existing)
                else:
                    logger.debug(
                        f"Cached predictions for {symbol} are too old (age: {age}, max: {max_age_days} days)"
                    )
        except Exception as e:
            logger.debug(f"Error getting cached predictions fallback for {symbol}: {e}")
        
        return None

    def _cleanup_old_predictions(self, symbol: str, user_id: Optional[int] = None) -> None:
        """Delete old unverified predictions for a symbol before storing new ones
        
        Args:
            symbol: Cryptocurrency symbol
            user_id: User ID to filter by (None for global predictions)
        """
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            
            if user_id is None:
                # Clean up global predictions (user_id IS NULL)
                sql = normalize_placeholders(
                    "DELETE FROM ai_predictions WHERE symbol = %s AND is_verified = FALSE AND user_id IS NULL"
                )
                cursor.execute(sql, (symbol.upper(),))
            else:
                # Clean up user-specific predictions
                sql = normalize_placeholders(
                    "DELETE FROM ai_predictions WHERE symbol = %s AND is_verified = FALSE AND user_id = %s"
                )
                cursor.execute(sql, (symbol.upper(), user_id))
            
            deleted_count = cursor.rowcount
            conn.commit()
            conn.close()
            
            if deleted_count > 0:
                logger.debug(f"Cleaned up {deleted_count} old predictions for {symbol} (user_id={'NULL' if user_id is None else user_id})")
        except Exception as e:
            logger.warning(f"Error cleaning up old predictions for {symbol}: {e}")

    def _store_prediction(
        self,
        user_id: Optional[int],
        symbol: str,
        prediction_type: str,
        predicted_price: float,
        confidence_percent: float,
        reasoning: str,
        model_name: str,
        created_at: str,
    ) -> int:
        """Store a prediction in the database
        
        Args:
            user_id: User ID (None for global predictions stored with user_id = NULL)
            symbol: Cryptocurrency symbol
            prediction_type: Type of prediction (24h, week, month, year)
            predicted_price: Predicted price
            confidence_percent: Confidence percentage
            reasoning: Prediction reasoning text
            model_name: AI model name used
            created_at: Creation timestamp
            
        Returns:
            Prediction ID
        """
        try:
            conn = get_db_connection()
            cursor = conn.cursor()

            sql = normalize_placeholders(
                """
                INSERT INTO ai_predictions
                (user_id, symbol, prediction_type, predicted_price, confidence_percent,
                 prediction_reasoning, model_name, created_at, is_verified)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            )

            prediction_id = execute_insert_and_get_id(
                cursor,
                sql,
                (
                    user_id,  # None for global predictions
                    symbol.upper(),
                    prediction_type,
                    predicted_price,
                    confidence_percent,
                    reasoning,
                    model_name,
                    created_at,
                    False,
                ),
            )

            conn.commit()
            conn.close()

            return prediction_id

        except Exception as e:
            logger.error(f"Error storing prediction: {e}", exc_info=True)
            raise

    def _format_predictions_response(
        self, predictions: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """Format predictions for API response"""
        result = {}
        for pred in predictions:
            pred_type = pred["prediction_type"]
            result[pred_type] = {
                "predicted_price": pred["predicted_price"],
                "confidence_percent": pred["confidence_percent"],
                "reasoning": pred.get("reasoning", ""),
                "model_name": pred.get("model_name", self.model_name),
                "created_at": pred["created_at"],
                "is_verified": pred.get("is_verified", False),
            }
        return result

    async def verify_predictions(self, symbol: str) -> None:
        """
        Verify past predictions against actual prices
        This should be run periodically by a background task
        """
        try:
            conn = get_db_connection()
            cursor = conn.cursor()

            # Find unverified predictions that should have been realized
            sql = normalize_placeholders(
                """
                SELECT id, prediction_type, predicted_price, created_at
                FROM ai_predictions
                WHERE symbol = %s AND is_verified = FALSE
            """
            )
            cursor.execute(sql, (symbol.upper(),))
            rows = cursor.fetchall()
            conn.close()

            # Get current price
            prices = await multi_exchange_price_service.get_current_prices([symbol])
            if symbol not in prices:
                return

            current_price = prices[symbol]
            now = datetime.now(timezone.utc)

            for row in rows:
                pred_id, pred_type, predicted_price, created_at_str = row
                created_at = datetime.fromisoformat(
                    created_at_str.replace("Z", "+00:00")
                )

                # Check if prediction period has passed
                periods = {
                    "24h": timedelta(hours=24),
                    "week": timedelta(days=7),
                    "month": timedelta(days=30),
                    "year": timedelta(days=365),
                }

                period = periods.get(pred_type)
                if not period:
                    continue

                if now - created_at >= period:
                    # Prediction period has passed, verify it
                    accuracy_percent = self._calculate_accuracy(
                        predicted_price, current_price
                    )

                    conn = get_db_connection()
                    cursor = conn.cursor()

                    update_sql = normalize_placeholders(
                        """
                        UPDATE ai_predictions
                        SET is_verified = TRUE,
                            actual_price_at_target = %s,
                            accuracy_percent = %s
                        WHERE id = %s
                    """
                    )
                    cursor.execute(update_sql, (current_price, accuracy_percent, pred_id))
                    conn.commit()
                    conn.close()

                    logger.info(
                        f"Verified prediction {pred_id} for {symbol} {pred_type}: "
                        f"predicted {predicted_price}, actual {current_price}, accuracy {accuracy_percent:.1f}%"
                    )

        except Exception as e:
            logger.error(
                f"Error verifying predictions for {symbol}: {e}", exc_info=True
            )

    def _calculate_accuracy(
        self, predicted_price: float, actual_price: float
    ) -> float:
        """Calculate prediction accuracy percentage (0-100)"""
        if actual_price == 0:
            return 0.0

        error_percent = abs((predicted_price - actual_price) / actual_price) * 100
        accuracy = max(0.0, 100.0 - error_percent)
        return accuracy

    async def get_performance_stats(
        self, user_id: int, symbol: Optional[str] = None, model_name: Optional[str] = None
    ) -> Dict[str, Any]:
        """Get performance statistics for predictions"""
        try:
            conn = get_db_connection()
            cursor = conn.cursor()

            conditions = ["user_id = %s", "is_verified = TRUE"]
            params = [user_id]

            if symbol:
                conditions.append("symbol = %s")
                params.append(symbol.upper())

            if model_name:
                conditions.append("model_name = %s")
                params.append(model_name)

            sql = normalize_placeholders(
                f"""
                SELECT 
                    COUNT(*) as total_predictions,
                    AVG(accuracy_percent) as avg_accuracy,
                    model_name,
                    symbol
                FROM ai_predictions
                WHERE {' AND '.join(conditions)}
                GROUP BY model_name, symbol
            """
            )

            cursor.execute(sql, tuple(params))
            rows = cursor.fetchall()
            conn.close()

            stats = {
                "total_predictions": 0,
                "average_accuracy": 0.0,
                "by_model": {},
                "by_symbol": {},
            }

            total_accuracy = 0.0
            count = 0

            for row in rows:
                total, avg_acc, model, sym = row
                stats["total_predictions"] += total
                total_accuracy += avg_acc * total if avg_acc else 0
                count += total

                if model:
                    if model not in stats["by_model"]:
                        stats["by_model"][model] = {"count": 0, "avg_accuracy": 0.0}
                    stats["by_model"][model]["count"] += total
                    stats["by_model"][model]["avg_accuracy"] = avg_acc or 0.0

                if sym:
                    if sym not in stats["by_symbol"]:
                        stats["by_symbol"][sym] = {"count": 0, "avg_accuracy": 0.0}
                    stats["by_symbol"][sym]["count"] += total
                    stats["by_symbol"][sym]["avg_accuracy"] = avg_acc or 0.0

            if count > 0:
                stats["average_accuracy"] = total_accuracy / count

            return stats

        except Exception as e:
            logger.error(f"Error getting performance stats: {e}", exc_info=True)
            return {
                "total_predictions": 0,
                "average_accuracy": 0.0,
                "by_model": {},
                "by_symbol": {},
            }


# Singleton instance
ai_advisor_service = AIAdvisorService()


async def background_ai_advisor_updater():
    """Background task to periodically generate/update AI predictions for all unique symbols (once per day)"""
    import asyncio
    from ..core.config import settings

    while True:
        try:
            # Wait for the interval before starting (daily: 24 hours)
            await asyncio.sleep(settings.ai_prediction_interval_hours * 3600)

            logger.info("🔄 Starting AI advisor prediction update cycle for all symbols")

            # Query all unique symbols from portfolio_items table
            conn = get_db_connection()
            cursor = conn.cursor()
            sql = normalize_placeholders(
                "SELECT DISTINCT symbol FROM portfolio_items WHERE symbol IS NOT NULL"
            )
            cursor.execute(sql)
            rows = cursor.fetchall()
            conn.close()

            all_symbols = [row[0] for row in rows if row[0]]

            if not all_symbols:
                logger.warning("No symbols found in database, skipping prediction generation")
                continue

            logger.info(f"📊 Found {len(all_symbols)} unique symbols to generate predictions for")

            # Process symbols sequentially with delays to avoid rate limits
            processed_count = 0
            for symbol in all_symbols:
                try:
                    # Generate predictions with user_id=None for global predictions
                    await ai_advisor_service.generate_predictions(
                        user_id=None,  # None = global predictions (stored with user_id = NULL)
                        symbol=symbol,
                        force_regenerate=False,  # Only generate if needed (check age)
                    )
                    processed_count += 1
                    logger.info(f"✅ Updated predictions for {symbol} ({processed_count}/{len(all_symbols)})")

                    # Add delay between predictions to avoid rate limits
                    # Process one symbol per hour to spread throughout the day
                    if processed_count < len(all_symbols):
                        delay_seconds = (settings.ai_prediction_interval_hours * 3600) / len(all_symbols)
                        delay_seconds = min(delay_seconds, 3600)  # Max 1 hour delay
                        logger.debug(f"⏳ Waiting {delay_seconds:.0f} seconds before next prediction...")
                        await asyncio.sleep(delay_seconds)

                except Exception as e:
                    logger.error(
                        f"Error generating predictions for {symbol}: {e}",
                        exc_info=True,
                    )
                    # Continue with next symbol even if one fails
                    continue

            logger.info(f"✅ AI advisor prediction update cycle completed: {processed_count}/{len(all_symbols)} symbols processed")

        except Exception as e:
            logger.error(f"Error in AI advisor updater: {e}", exc_info=True)
            await asyncio.sleep(3600)  # Wait 1 hour before retrying


async def background_prediction_verifier():
    """Background task to verify past predictions against actual prices"""
    import asyncio

    while True:
        try:
            # Run verification every 6 hours
            await asyncio.sleep(6 * 3600)

            logger.info("🔄 Starting prediction verification cycle")

            # Get all symbols with unverified predictions
            conn = get_db_connection()
            cursor = conn.cursor()

            sql = normalize_placeholders(
                "SELECT DISTINCT symbol FROM ai_predictions WHERE is_verified = FALSE"
            )
            cursor.execute(sql)
            symbols = [row[0] for row in cursor.fetchall()]
            conn.close()

            if not symbols:
                logger.debug("No unverified predictions found")
                continue

            logger.info(f"🔄 Verifying predictions for {len(symbols)} symbols")

            # Verify predictions for each symbol
            for symbol in symbols:
                try:
                    await ai_advisor_service.verify_predictions(symbol)
                    logger.debug(f"✅ Verified predictions for {symbol}")
                except Exception as e:
                    logger.error(
                        f"Error verifying predictions for {symbol}: {e}",
                        exc_info=True,
                    )
                    continue

            logger.info("✅ Prediction verification cycle completed")

        except Exception as e:
            logger.error(f"Error in prediction verifier: {e}", exc_info=True)
            await asyncio.sleep(3600)  # Wait 1 hour before retrying
